CREATE SEQUENCE hibernate_sequence START WITH 1 INCREMENT BY 1
CREATE TABLE AUTHOR (ID INTEGER NOT NULL, email VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (ID))
CREATE TABLE POST (ID INTEGER NOT NULL, content CLOB NOT NULL, published BOOLEAN NOT NULL, title VARCHAR(255) NOT NULL, author_id INTEGER NOT NULL, CREATE_DATE TIMESTAMP, PRIMARY KEY (ID))
CREATE TABLE POST_TAG (post_id INTEGER NOT NULL, tag_id INTEGER NOT NULL, PRIMARY KEY (post_id, tag_id))
CREATE TABLE TAG (ID INTEGER NOT NULL, name VARCHAR(255) NOT NULL, visible BOOLEAN NOT NULL, PRIMARY KEY (ID))
ALTER TABLE AUTHOR ADD CONSTRAINT UK_f7gncwa3jekapqh48kf23bbts UNIQUE (email)
ALTER TABLE TAG ADD CONSTRAINT UK_q8beoh2i5vhonh3itrfjsmunn UNIQUE (name)
ALTER TABLE POST ADD CONSTRAINT FK7d8xtm26wx2kgacfavd46v8rq FOREIGN KEY (author_id) REFERENCES AUTHOR
ALTER TABLE POST_TAG ADD CONSTRAINT FK2nd3649tur2dtbghwm7hu1kfa FOREIGN KEY (tag_id) REFERENCES TAG
ALTER TABLE POST_TAG ADD CONSTRAINT FKnjdgyr1qvsbifp3vt75o04ovs FOREIGN KEY (post_id) REFERENCES POST
